apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: adityabhattad/question-answer
      context: question_answer
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: adityabhattad/rag-uploader
      context: rag_uploader
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: adityabhattad/query-preprocessing
      context: query_preprocessing
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*