apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: adityabhattad/question-answer
      context: question_answer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.py'
            dest: .
  