apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-preprocessing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-preprocessing
  template:
    metadata:
      labels:
        app: query-preprocessing
    spec:
      containers:
        - name: query-preprocessing
          image: adnantd/query-preprocessing
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GOOGLE_API_KEY
            - name: OLLAMA_URL
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: OLLAMA_URL
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GROQ_API_KEY
            - name: CLAUDE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: CLAUDE_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
            - name: REDIS_HOST
              value: redis-service
---
apiVersion: v1
kind: Service
metadata:
  name: query-preprocessing-service
spec:
  selector:
    app: query-preprocessing
  type: ClusterIP
  ports:
    - name: query-preprocessing
      protocol: TCP
      port: 8000
      targetPort: 80
