apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-answer
  template:
    metadata:
      labels:
        app: question-answer
    spec:
      containers:
        - name: question-answer
          image: adnantd/question-answer
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GOOGLE_API_KEY
            - name: OLLAMA_URL
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: OLLAMA_URL
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GROQ_API_KEY
            - name: TAVILY_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: TAVILY_AI_API_KEY
            - name: CONNECTION_STRING
              value: 'postgresql+psycopg2://admin:admin@postgres-service:5432/vectordb'
            - name: CONNECTION_NAME
              value: 'vectordb'
---
apiVersion: v1
kind: Service
metadata:
  name: qa-service
spec:
  selector:
    app: question-answer
  type: ClusterIP
  ports:
    - name: question-answer
      protocol: TCP
      port: 8000
      targetPort: 80
